### ISSUE TITLE
PHP Errors on VMPayment plugin

### ISSUE THREAD

**Issue by grandpolar** [PayGate/PayWeb_VirtueMart#4]
VMPayment gives the following errors when running on Virtuemart 4.2.0 and Joomla 4.
The plugin installs correctly and is configured  correctly. When displaying the  cart the following errors occur and the checkout page does not display the Paygate payment option.

Deprecated: Required parameter $html follows optional parameter $selected in /home/gpdev1c/public_html/a2348/plugins/vmpayment/paygate/paygate.php on line 634

Deprecated: Required parameter $counter follows optional parameter $prices in /home/gpdev1c/public_html/a2348/plugins/vmpayment/paygate/paygate.php on line 660

**Comment by grandpolar** [comment]
![Paygate 1-04 Error](https://github.com/PayGate/PayWeb_VirtueMart/assets/3304455/8f1b65e5-9814-4154-a468-2d7e6b1b04a7)
Error Screen

**Comment by bruce-atkinson** [comment]
Hi @grandpolar 

These two functions are overriding functions from the Virtumart core library, therefore, we cannot change the signature of these functions until the platform does; these deprecated warnings would not be the result of the payment method not showing on the checkout page.

We have suppressions for both functions added for future releases, but in order to debug this issue further, a ticket will need to be logged by sending an email to [support@payfast.help](mailto:support@payfast.help).
